import { TrendingUp, TrendingDown, AlertCircle } from 'lucide-react';
import './PredictionResult.css';

export default function PredictionResult({ result }) {
  if (!result) return null;

  const { ticker, prediction, probability, timestamp } = result;
  
  const isUp = prediction === 'UP';
  const confidence = ((probability || 0.6) * 100).toFixed(1);

  return (
    <div className="prediction-result glass-panel fade-in">
      <div className="result-header">
        <h3>{ticker} Prediction</h3>
        {timestamp && <span className="timestamp">{new Date(timestamp).toLocaleString()}</span>}
      </div>

      <div className="result-content">
        <div className={`prediction-badge ${isUp ? 'up' : 'down'}`}>
          {isUp ? <TrendingUp size={32} /> : <TrendingDown size={32} />}
          <span className="direction">{prediction}</span>
        </div>
        
        <div className="confidence-meter">
          <div className="confidence-label">
            <span>Model Confidence</span>
            <span>{confidence}%</span>
          </div>
          <div className="progress-bar-bg">
            <div 
              className={`progress-bar-fill ${isUp ? 'bg-success' : 'bg-danger'}`} 
              style={{ width: `${confidence}%` }}
            ></div>
          </div>
        </div>
      </div>

      <div className="disclaimer">
        <AlertCircle size={14} className="disclaimer-icon" />
        <p>Not financial advice. Predictions are generated by an AI model and may not be accurate.</p>
      </div>
    </div>
  );
}
